FROM --platform=linux/amd64 ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5
COPY OpenCL.def /tmp/OpenCL.def
RUN x86_64-w64-mingw32-dlltool \
      -d /tmp/OpenCL.def \
      -l /usr/x86_64-w64-mingw32/lib/libOpenCL.dll.a \
      -D OpenCL.dll
